s = input("string operations")
print("Gives the uppercase of the string")
print(s.upper())
print("Gives the index of a character in the given string")
print(s.find('i'))
print("Gives the index of a string in the given string")
print(s.find('happens'))
print("Gives the index of a string in the given string")
print(s.replace('happens', 'well'))
print("Shit" in s)
print(s+"See the string is unaffected since it does not affect the main object")
